version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "9000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  app-node:
    image: book-a-desk:local
    container_name: book-a-desk
    ports:
      - "5000:80"
    depends_on:
      - "dynamodb-local"
    links:
      - "dynamodb-local"
    environment:
      AWS_REGION: 'ca-central-1'
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
      DynamoDB:ReservationTableName: 'ReservationEvents'
      DynamoDB:OfficeTableName: 'Offices'
      AWS_DEVELOPMENTSTORAGE: 'true'
      AWS_DEVELOPMENTURL: 'http://dynamodb-local:8000'
      DOMAINNAME: 'broadsign.com'
      FeatureFlags:BookingCancellation: 'true'
      Okta:OktaDomain: 'localhost'
      Okta:OktaAudience: 'test'
      FeatureFlags:GetBookings: 'true'