# Usage Notes
# Add the following environment variables to your CircleCI project:

## AWS
# (see https://circleci.com/orbs/registry/orb/circleci/aws-cli)
# - AWS_REGION

## AWS ECR (Platform)
# (see https://circleci.com/orbs/registry/orb/circleci/aws-ecr)
# Note: These are provided by the platform-aws-ecr context
# - AWS_ECR_ACCESS_KEY_ID
# - AWS_ECR_SECRET_ACCESS_KEY
# - AWS_ECR_ACCOUNT_URL

version: 2.1
workflows:
  pull-request:
    when:
      equal: ["trunk", << pipeline.git.branch >>]
    jobs:
      - build_and_test
      - build_image:
          requires:
            - build_and_test

  production:
    unless:
      equal: ["trunk", << pipeline.git.branch >>]
    jobs:
      - build_and_test
      - build_image:
          requires:
            - build_and_test
      - deploy:
          name: deploy-to-dev
          ecr-account-url: ${AWS_ECR_ACCOUNT_URL_DEV}
          aws-account-id: ${AWS_ACCOUNT_DEV}
          authenticate-aws:
            - authenticate-aws-book-a-desk-dev
          context:
            - aws-credentials
          requires:
            - build_image
      - deploy:
          name: deploy-to-test
          ecr-account-url: ${AWS_ECR_ACCOUNT_URL_TEST}
          aws-account-id: ${AWS_ACCOUNT_TEST}
          authenticate-aws:
            - authenticate-aws-book-a-desk-test
          context:
            - aws-credentials
          requires:
            - deploy-to-dev

orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-ecs: circleci/aws-ecs@2.0.0
  aws-cli: circleci/aws-cli@1.3.0

parameters:
  docker-repo:
    type: string
    default: book-a-desk

  docker-img-version:
    type: string
    default: "build-<< pipeline.number >>"

  docker-tar-filename:
    type: string
    default: "book-a-desk_latest.tar"

commands:
  publish-test-results:
    description: Converts and publishes test results (.NET only)
    parameters:
      path:
        description: Path to the test results folder
        type: string
    steps:
      - run:
          name: Convert test results to CircleCI format
          command: |
            dotnet tool install --global trx2junit
            export PATH="$PATH:$HOME/.dotnet/tools"
            trx2junit << parameters.path >>/*.trx
      - store_test_results:
          path: << parameters.path >>
  deploy-to-ecr:
    parameters:
      ecr-account-url:
        type: string
      aws-account-id:
        type: string
    steps:
      - run:
          name: Load Docker image
          command: docker load -i ./<< pipeline.parameters.docker-tar-filename >>
      - run:
          name: Tag Docker image for ECR
          command: |
            docker tag \
              << pipeline.parameters.docker-repo >>:<< pipeline.parameters.docker-img-version >> \
              "<< parameters.ecr-account-url >>/<< pipeline.parameters.docker-repo >>:<< pipeline.parameters.docker-img-version >>"
      - run:
          name: Docker login
          command: aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin << parameters.aws-account-id >>.dkr.ecr.${AWS_REGION}.amazonaws.com
      - aws-ecr/push-image:
          repo: << pipeline.parameters.docker-repo >>
          tag: << pipeline.parameters.docker-img-version >>
  log-aws-identity:
    parameters:
      profile:
        type: string
        default: ${AWS_PROFILE}
    steps:
      - run:
          name: Log AWS identity <<# parameters.profile >>(profile=<< parameters.profile >>)<</ parameters.profile >>
          command: aws sts get-caller-identity <<# parameters.profile >> --profile << parameters.profile >> <</ parameters.profile >> --region $AWS_REGION || true
  authenticate-aws-book-a-desk-dev:
    description: "Configure AWS credentials for Book A Desk Dev"
    steps:
      - run:
          name: "Initialize BASH_ENV variables"
          command: |
            echo "export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_DEV}" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_DEV}" >> $BASH_ENV
            echo $AWS_SECRET_ACCESS_KEY_ID
  authenticate-aws-book-a-desk-test:
    description: "Configure AWS credentials for Book A Desk Test"
    steps:
      - run:
          name: "Initialize BASH_ENV variables"
          command: |
            echo "export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_TEST}" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_TEST}" >> $BASH_ENV
jobs:
  build_and_test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0-alpine
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout
      - run:
          name: Build
          command: dotnet build
      - run:
          name: Run unit tests
          command: |
            dotnet test \
            --verbosity normal \
            --filter "FullyQualifiedName~Tests" \
            --results-directory ./tests/unit/results \
            --logger "trx"
      - publish-test-results:
          path: ./tests/unit/results

  build_image:
    docker:
      - image: circleci/buildpack-deps:latest
        user: root
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t << pipeline.parameters.docker-repo >>:<< pipeline.parameters.docker-img-version >> \
              --build-arg AWSREGION=$AWS_REGION .
      - run:
          name: Save Docker image
          command: |
            docker save \
              -o << pipeline.parameters.docker-tar-filename >> \
              << pipeline.parameters.docker-repo >>:<< pipeline.parameters.docker-img-version >>
      - persist_to_workspace:
          root: .
          paths:
            - << pipeline.parameters.docker-tar-filename >>

  deploy:
    machine: true
    parameters:
      ecr-account-url:
        type: string
      aws-account-id:
        type: string
      authenticate-aws:
        type: steps
    
    steps:
      - attach_workspace:
          at: ./
      - steps: << parameters.authenticate-aws >>
      - log-aws-identity
      - aws-cli/setup:
          aws-region: AWS_REGION
      - deploy-to-ecr:
          ecr-account-url: << parameters.ecr-account-url >>
          aws-account-id: << parameters.aws-account-id >>
      - aws-ecr/push-image:
          repo: << pipeline.parameters.docker-repo >>
          tag: << pipeline.parameters.docker-img-version >>
#      - aws-ecs/update-service:
#          cluster-name: 'arn:aws:ecs:${AWS_REGION}:<< parameters.aws-account-id >>:cluster/Book-A-Desk-Cluster'

#          container-image-name-updates: 'container=Book-A-Desk-Container,tag=<< pipeline.parameters.docker-img-version >>'
#          service-name: 'Book-A-Desk'
#          family: 'Book-A-Desk-Backend'