 version: 2.1

 jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0-alpine
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD 
    
    steps:
       - checkout
       - run: 
           name: Build
           command: dotnet build
       - run:
           name: Run Tests
           command: dotnet test --no-build --logger "trx"
       - run:
           name: Save Test Results
           when: always
           command: |
             export PATH="$PATH:/root/.dotnet/tools"
             dotnet tool install -g trx2junit
             trx2junit *.Tests/**/TestResults/*.trx
       - store_test_results: 
           path: "test_result.xml"
