 version: 2.1

 jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0-alpine
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD 
    
    steps:
       - checkout
       - run: dotnet build
