 version: 2.1

 jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0-alpine
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD 
    
    steps:
       - checkout
       - run: dotnet build
       - run: dotnet test --results-directory:test_results --collect:"XPlat Code Coverage"
       - store_artifacts:
           path: ./test_results
