version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "9000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  app-node:
    image: book-a-desk:local
    container_name: book-a-desk
    ports:
      - "5000:80"
    depends_on:
      - "dynamodb-local"
    links:
      - "dynamodb-local"
    env_file:
      - "./.env"